font_family JetBrainsMono Nerd Font
font_size 11.5
background #151515
foreground #f2e7d5
selection_background #ff7a1a
selection_foreground #151515
cursor #ff9f3f
url_color #ff9f3f
active_tab_background #ff7a1a
active_tab_foreground #151515
inactive_tab_background #242424
inactive_tab_foreground #d6cbbd
tab_bar_background #101010
window_padding_width 10
enable_audio_bell no
confirm_os_window_close 0
