color_theme = "cinderos_ember"
theme_background = False
truecolor = True
rounded_corners = False
graph_symbol = "block"
update_ms = 1500
proc_sorting = "cpu lazy"
proc_tree = False
show_gpu_info = "Auto"
