efiSystemPartition: "/boot/efi"
userSwapChoices:
  - none
  - file
  - partition
  - zram
drawNestedPartitions: true
defaultFileSystemType: btrfs
availableFileSystemTypes:
  - btrfs
  - ext4
  - xfs
initialPartitioningChoice: erase
allowManualPartitioning: true

