services:
  - name: NetworkManager
    mandatory: true
  - name: systemd-resolved
    mandatory: true
  - name: ufw
    mandatory: true
  - name: apparmor
    mandatory: true
  - name: upower
    mandatory: true
  - name: seatd
    mandatory: true
  - name: greetd
    mandatory: true
  - name: systemd-timesyncd
    mandatory: true
  - name: power-profiles-daemon
    mandatory: true
  - name: switcheroo-control
    mandatory: true
  - name: earlyoom
    mandatory: true
  - name: cinder-hardware-setup
    mandatory: true

disable:
  - systemd-networkd
  - bluetooth
  - docker
  - cups
  - fwupd
  - systemd-oomd
  - cinder-snapshot-setup
  - sshd
  - fail2ban
  - usbguard
  - clamav-daemon
  - clamav-freshclam
  - auditd
