#!/usr/bin/env bash
set -euo pipefail

profile_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

code_paths=(
  "$profile_dir/scripts"
  "$profile_dir/airootfs/usr/local/bin"
  "$profile_dir/airootfs/root/customize_airootfs.sh"
  "$profile_dir/airootfs/etc/calamares/scripts"
)

skip_files=(
  "$profile_dir/scripts/check-code-style.sh"
  "$profile_dir/scripts/check-visible-text.sh"
)

rough_pattern='TODO|FIXME|HACK|placeholder|scaffold|dummy|mock|ChatGPT|Copilot|AI-generated|generated by|generated from|provided JSON spec|current system state|report capture|evidence-based|readiness|tooling|workflow|boilerplate|lorem ipsum|as an AI'

is_skipped() {
  local file="$1"
  local skip

  for skip in "${skip_files[@]}"; do
    if [[ "$file" == "$skip" ]]; then
      return 0
    fi
  done

  return 1
}

hits=""
while IFS= read -r -d '' file; do
  if is_skipped "$file"; then
    continue
  fi

  file_hits="$(grep -InE "$rough_pattern" "$file" || true)"
  if [[ -n "$file_hits" ]]; then
    hits+="$file_hits"$'\n'
  fi
done < <(
  find "${code_paths[@]}" -type f -print0
)

if [[ -n "$hits" ]]; then
  echo "Code still has leftover draft or generated-looking wording:" >&2
  printf '%s' "$hits" >&2
  exit 1
fi

echo "CinderOS code style guardrail looks clean."
